### ISSUE TITLE
Installing the plugin

### ISSUE THREAD

**Issue by thomaswinterstetter** [experience/smartdown.craft-plugin#12] opened 2018-04-12 18:37 UTC
Composer was unable to install the updates.

Error: An error occurred

Output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

---

Error: An error occurred

Output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for experience/smartdown 3.0.0 -> satisfiable by experience/smartdown[3.0.0].
    - experience/smartdown 3.0.0 requires php ^7.1.0 -> your PHP version (7.1.15) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by monooso** [comment] 2018-06-05 16:13
@thomaswinterstetter Sorry for the (very) slow response, I completely missed this notification.

This looks like a duplicate of #11. I'll sort that out, and hopefully it should fix your problem, too.

**Closed by monooso** 2018-06-05 16:13 UTC
